name: Api Unit Test Checks
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.py'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  api_unit_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: API Unit Tests (Library)
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
