name: Commit Update

on:
  push:
      paths:
          - "docs/data_dictionary/**"

jobs:
    build:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, 'Skip')"
        permissions:
            # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.||
            contents: write

        defaults:
            run:
                working-directory: docs/data_dictionary

        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.11

            - name: Cache Dependencies
              id: cache
              uses: actions/cache@v3
              with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-dictionary-${{ hashFiles('**/requirements.txt') }}

            - name: Install dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: |
                  pip install -r ./requirements.txt

            - name: Create changes
              run: |
                  echo "From commit workflow" >> commitmessage.txt
                  git status

            # - name: Commit changes
            #   uses: stefanzweifel/git-auto-commit-action@v5
            #   with:
            #       commit_message: Test commit Skip

