name: Commit Changes

on:
  push:
      paths:
          - "docs/data_dictionary/**"

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.||
            contents: write

        defaults:
            run:
                working-directory: docs/data_dictionary

        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.11

            - name: Create changes
              run: |
                  echo "From commit workflow" >> commitmessage.txt
                  git status

            - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: Test commit

    api_unit_test:
        needs: build
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.11]
        steps:
            - run: 'echo "No build required!!"'
        # steps:
        # - name: Checkout repository
        #   uses: actions/checkout@v4

        # - name: Run generic API workflow
        #   run: |
        #     gh workflow run generic-api.yml -f tags=false
        #   env:
        #     GITHUB_TOKEN: ${{ secrets.PAT }}
