name: "Pull Request Commenter"

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      
    - name: Install dependencies
      run: npm install glob
      
    - name: Add comment to PR with labels
      uses: actions/github-script@v5
      with:
        script: |
          const glob = require('glob');
          const issueNumber = context.payload.pull_request.number;
          const prFiles = await github.rest.pulls.listFiles({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: issueNumber,
          });

          const labelMappings = {
            'Vue': 'frontend/**/*.js',
            'Python API': 'services/api/**/*.py',
          };

          const labelsToAdd = Object.keys(labelMappings).filter(label =>
            prFiles.data.some(prFile => glob.sync(labelMappings[label], { cwd: github.workspace }).includes(prFile.filename)),
          );

          const message = `Thanks for your pull request! Based on the files changed, this PR would be labeled with the following labels: ${labelsToAdd.join(', ')}`;
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issueNumber,
            body: message,
          });
