# name: Pull Request Labeler

# on:
#   pull_request:
#     types:
#       - opened
#       - synchronize

# jobs:
#   label:
#     runs-on: ubuntu-latest
    
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
        
#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: 14
        
#       - name: Install dependencies
#         run: npm install
        
#       - name: Run labeler action
#         uses: actions/labeler@v4
#         with:
#           repo-token: ${{ secrets.GITHUB_TOKEN }}
#           configuration-path: .github/labeler.yml


name: "Pull Request Labeler"
# on:
#   pull_request:
#     types:
#       - opened
#       - synchronize

on:
  pull_request:
    types: [ labeled ]

# jobs:
#   triage:
#     permissions:
#       contents: read
#       pull-requests: write
#     if: ${{ github.event.label.name == 'bug' }}
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/labeler@v4


jobs:
  build:
    if: ${{ github.event.label.name == 'bug' }}
    triage:
      permissions:
        contents: read
        pull-requests: write
      runs-on: ubuntu-latest
      steps:
      - uses: actions/labeler@v4
