name: Frontend Unit Test
on:
    pull_request:
        types: [opened, synchronize, reopened]
        paths:
            - "**.js"
            - "**.ts"
            - "**.jsx"
            - "**.tsx"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  npm_unit_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    - name: NPM Unit Tests
      run: |
        cd frontend
        npm install
        npm run test
