name: Update Wiki

on:
    push:
        paths:
            - "docs/data_dictionary/src/**"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.x # Replace with your desired Python version

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r docs/data_dictionary/requirements.txt

            - name: Update Wiki
              run: python docs/data_dictionary/docs.py --refresh=$(r) --filename=$(f)
              env:
                  r: ${{ github.event.after }}
                  f: docs/data_dictionary/wiki.md # Replace with the actual output file path
